apiVersion: v1
kind: PersistentVolume
metadata:
  name: iscsi-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  iscsi:
     targetPortal: '10.0.2.15'
     portals: ['10.0.2.15:3260']
     iqn: 'iqn.2020-12.com.redhat:server'
     lun: 0
     fsType: 'ext4'
#     initiatorName: iqn.2020-12.com.redhat:client
     readOnly: false
